# Generated by Django 5.0.1 on 2026-02-24 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('nuevo', 'Nuevo'), ('como_nuevo', 'Como Nuevo'), ('buen_estado', 'Buen Estado'), ('usado', 'Usado')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('donation', 'Donación'), ('sale', 'Venta'), ('swap', 'Intercambio')], max_length=20)),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='disponible', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='marketplace.category')),
                ('seller', models.ForeignKey(db_column='seller_id', on_delete=django.db.models.deletion.RESTRICT, related_name='products_selling', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('order_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ForeignKey(db_column='products_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.products')),
            ],
            options={
                'verbose_name_plural': 'Images',
                'db_table': 'images',
                'ordering': ['products', 'order_number'],
            },
        ),
        migrations.CreateModel(
            name='ForumQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='marketplace.forumquestion')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='forum_questions', to=settings.AUTH_USER_MODEL)),
                ('products', models.ForeignKey(db_column='products_id', on_delete=django.db.models.deletion.CASCADE, related_name='forum_questions', to='marketplace.products')),
            ],
            options={
                'db_table': 'forum_questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('donation', 'Donation'), ('sale', 'Sale'), ('swap', 'Swap')], max_length=20)),
                ('seller_confirmation', models.BooleanField(default=False)),
                ('seller_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_confirmation', models.BooleanField(default=False)),
                ('buyer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.RESTRICT, related_name='transactions_buying', to=settings.AUTH_USER_MODEL)),
                ('products', models.OneToOneField(db_column='products_id', on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='marketplace.products')),
                ('seller', models.ForeignKey(db_column='seller_id', on_delete=django.db.models.deletion.RESTRICT, related_name='transactions_selling', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['seller'], name='products_seller__c70854_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['category'], name='products_categor_4083ff_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['status'], name='products_status_a30e64_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['status', 'category'], name='idx_products_available'),
        ),
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['products', 'order_number'], name='images_product_756ae9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='images',
            unique_together={('products', 'order_number')},
        ),
        migrations.AddIndex(
            model_name='forumquestion',
            index=models.Index(fields=['products'], name='forum_quest_product_bb78c8_idx'),
        ),
        migrations.AddIndex(
            model_name='forumquestion',
            index=models.Index(fields=['user'], name='forum_quest_user_id_3d3b46_idx'),
        ),
        migrations.AddIndex(
            model_name='forumquestion',
            index=models.Index(fields=['parent'], name='forum_quest_parent__e4b231_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['seller'], name='transaction_seller__083d37_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['buyer'], name='transaction_buyer_i_56e41a_idx'),
        ),
    ]
