# Generated by Django 5.0.1 on 2026-04-30 00:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('nuevo', 'New'), ('como_nuevo', 'Like New'), ('buen_estado', 'Good Condition'), ('usado', 'Used')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('donation', 'Donation'), ('sale', 'Sale'), ('swap', 'Swap')], max_length=20)),
                ('status', models.CharField(choices=[('disponible', 'Available'), ('pausado', 'Paused'), ('en_proceso', 'In Progress'), ('completado', 'Completed'), ('cancelado', 'Cancelled')], default='disponible', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='marketplace.category')),
                ('community', models.ForeignKey(blank=True, db_column='community_id', help_text='If set, this item is only visible to community members. If null, item is public.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_items', to='social.community')),
                ('seller', models.ForeignKey(db_column='seller_id', on_delete=django.db.models.deletion.RESTRICT, related_name='products_selling', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='marketplace.products')),
            ],
            options={
                'db_table': 'marketplace_productreaction',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('order_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='products_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.products')),
            ],
            options={
                'verbose_name_plural': 'Images',
                'ordering': ['product', 'order_number'],
            },
        ),
        migrations.CreateModel(
            name='ForumQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='marketplace.forumquestion')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='social.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_questions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_column='products_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='marketplace.products')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_comments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='marketplace.products')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('prohibited_item', 'Prohibited item'), ('misleading_description', 'Misleading description'), ('offensive_content', 'Offensive content'), ('possible_scam', 'Possible scam'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='marketplace.products')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_report',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('donation', 'Donation'), ('sale', 'Sale'), ('swap', 'Swap')], max_length=20)),
                ('seller_confirmation', models.BooleanField(default=False)),
                ('seller_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_confirmation', models.BooleanField(default=False)),
                ('buyer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pendiente', 'Pending'), ('confirmada', 'Confirmed'), ('completada', 'Completed'), ('cancelada', 'Cancelled')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.RESTRICT, related_name='transactions_buying', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(db_column='products_id', on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='marketplace.products')),
                ('seller', models.ForeignKey(db_column='seller_id', on_delete=django.db.models.deletion.RESTRICT, related_name='transactions_selling', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SwapTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('proposal_pending', 'Proposal Pending'), ('proposal_rejected', 'Proposal Rejected'), ('proposal_accepted', 'Proposal Accepted'), ('agenda_pending', 'Agenda Pending'), ('agenda_rejected', 'Agenda Rejected'), ('agenda_accepted', 'Agenda Accepted')], default='proposal_pending', max_length=30)),
                ('agenda_location', models.CharField(blank=True, max_length=255, null=True)),
                ('proposal_decided_at', models.DateTimeField(blank=True, null=True)),
                ('agenda_decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('proposed_product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='swap_proposals', to='marketplace.products')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swap_data', to='marketplace.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['seller'], name='marketplace_seller__8a7591_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['category'], name='marketplace_categor_896440_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['status'], name='marketplace_status_fc638b_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['status', 'category'], name='idx_products_available'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['community'], name='marketplace_communi_e7c502_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['community', 'status'], name='idx_comm_prod_avail'),
        ),
        migrations.AddIndex(
            model_name='productreaction',
            index=models.Index(fields=['product', 'type'], name='idx_pr_product_type'),
        ),
        migrations.AddIndex(
            model_name='productreaction',
            index=models.Index(fields=['user'], name='idx_pr_user'),
        ),
        migrations.AddConstraint(
            model_name='productreaction',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='uq_productreaction_product_user'),
        ),
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['product', 'order_number'], name='marketplace_product_1cfe7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='images',
            unique_together={('product', 'order_number')},
        ),
        migrations.AddIndex(
            model_name='forumquestion',
            index=models.Index(fields=['product'], name='marketplace_product_f79f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='forumquestion',
            index=models.Index(fields=['post'], name='marketplace_post_id_d7602d_idx'),
        ),
        migrations.AddIndex(
            model_name='forumquestion',
            index=models.Index(fields=['user'], name='marketplace_user_id_df1d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='forumquestion',
            index=models.Index(fields=['parent'], name='marketplace_parent__ff447a_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['product', 'created_at'], name='idx_comment_product_created'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['product'], name='idx_marketplace_report_product'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter'], name='idx_report_reporter'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('product', 'reporter'), name='uq_report_product_reporter'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['seller'], name='marketplace_seller__057004_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['buyer'], name='marketplace_buyer_i_e20c48_idx'),
        ),
        migrations.AddIndex(
            model_name='swaptransaction',
            index=models.Index(fields=['stage'], name='idx_swaptx_stage'),
        ),
        migrations.AddIndex(
            model_name='swaptransaction',
            index=models.Index(fields=['stage', 'created_at'], name='idx_swaptx_stage_created'),
        ),
        migrations.AddConstraint(
            model_name='transactionreview',
            constraint=models.UniqueConstraint(fields=('transaction', 'reviewer'), name='uq_transaction_review_reviewer'),
        ),
    ]
