# Generated by Django 5.0.1 on 2026-04-14 03:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('order_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Images',
                'ordering': ['product', 'order_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'marketplace_productreaction',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('prohibited_item', 'Prohibited item'), ('misleading_description', 'Misleading description'), ('offensive_content', 'Offensive content'), ('possible_scam', 'Possible scam'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'marketplace_report',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('donation', 'Donation'), ('sale', 'Sale'), ('swap', 'Swap')], max_length=20)),
                ('seller_confirmation', models.BooleanField(default=False)),
                ('seller_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_confirmation', models.BooleanField(default=False)),
                ('buyer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pendiente', 'Pending'), ('confirmada', 'Confirmed'), ('completada', 'Completed'), ('cancelada', 'Cancelled')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='products',
            new_name='marketplace_seller__8a7591_idx',
            old_name='products_seller__c70854_idx',
        ),
        migrations.RenameIndex(
            model_name='products',
            new_name='marketplace_categor_896440_idx',
            old_name='products_categor_4083ff_idx',
        ),
        migrations.RenameIndex(
            model_name='products',
            new_name='marketplace_status_fc638b_idx',
            old_name='products_status_a30e64_idx',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_url',
        ),
        migrations.AddField(
            model_name='products',
            name='community',
            field=models.ForeignKey(blank=True, db_column='community_id', help_text='If set, this item is only visible to community members. If null, item is public.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_items', to='social.community'),
        ),
        migrations.AddField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='products',
            name='condition',
            field=models.CharField(choices=[('nuevo', 'New'), ('como_nuevo', 'Like New'), ('buen_estado', 'Good Condition'), ('usado', 'Used')], max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('disponible', 'Available'), ('pausado', 'Paused'), ('en_proceso', 'In Progress'), ('completado', 'Completed'), ('cancelado', 'Cancelled')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='transaction_type',
            field=models.CharField(choices=[('donation', 'Donation'), ('sale', 'Sale'), ('swap', 'Swap')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['community'], name='marketplace_communi_e7c502_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['community', 'status'], name='idx_comm_prod_avail'),
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='marketplace.products'),
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='marketplace.forumquestion'),
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='social.communitypost'),
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='product',
            field=models.ForeignKey(blank=True, db_column='products_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='marketplace.products'),
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(db_column='products_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.products'),
        ),
        migrations.AddField(
            model_name='productreaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='marketplace.products'),
        ),
        migrations.AddField(
            model_name='productreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='marketplace.products'),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.RESTRICT, related_name='transactions_buying', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.OneToOneField(db_column='products_id', on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='marketplace.products'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(db_column='seller_id', on_delete=django.db.models.deletion.RESTRICT, related_name='transactions_selling', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionreview',
            name='reviewee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionreview',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.transaction'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['product', 'created_at'], name='idx_comment_product_created'),
        ),
        migrations.AddIndex(
            model_name='forumquestion',
            index=models.Index(fields=['product'], name='marketplace_product_f79f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='forumquestion',
            index=models.Index(fields=['post'], name='marketplace_post_id_d7602d_idx'),
        ),
        migrations.AddIndex(
            model_name='forumquestion',
            index=models.Index(fields=['user'], name='marketplace_user_id_df1d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='forumquestion',
            index=models.Index(fields=['parent'], name='marketplace_parent__ff447a_idx'),
        ),
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['product', 'order_number'], name='marketplace_product_1cfe7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='images',
            unique_together={('product', 'order_number')},
        ),
        migrations.AddIndex(
            model_name='productreaction',
            index=models.Index(fields=['product', 'type'], name='idx_pr_product_type'),
        ),
        migrations.AddIndex(
            model_name='productreaction',
            index=models.Index(fields=['user'], name='idx_pr_user'),
        ),
        migrations.AddConstraint(
            model_name='productreaction',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='uq_productreaction_product_user'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['product'], name='idx_marketplace_report_product'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter'], name='idx_report_reporter'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('product', 'reporter'), name='uq_report_product_reporter'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['seller'], name='marketplace_seller__057004_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['buyer'], name='marketplace_buyer_i_e20c48_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionreview',
            constraint=models.UniqueConstraint(fields=('transaction', 'reviewer'), name='uq_transaction_review_reviewer'),
        ),
    ]