# Generated by Django 5.0.1 on 2026-03-13 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('order_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Images',
                'ordering': ['product', 'order_number'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('donation', 'Donation'), ('sale', 'Sale'), ('swap', 'Swap')], max_length=20)),
                ('seller_confirmation', models.BooleanField(default=False)),
                ('seller_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_confirmation', models.BooleanField(default=False)),
                ('buyer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pendiente', 'Pending'), ('confirmada', 'Confirmed'), ('completada', 'Completed'), ('cancelada', 'Cancelled')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='products',
            new_name='marketplace_seller__8a7591_idx',
            old_name='products_seller__c70854_idx',
        ),
        migrations.RenameIndex(
            model_name='products',
            new_name='marketplace_categor_896440_idx',
            old_name='products_categor_4083ff_idx',
        ),
        migrations.RenameIndex(
            model_name='products',
            new_name='marketplace_status_fc638b_idx',
            old_name='products_status_a30e64_idx',
        ),
        migrations.AddField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='condition',
            field=models.CharField(choices=[('nuevo', 'New'), ('como_nuevo', 'Like New'), ('buen_estado', 'Good Condition'), ('usado', 'Used')], max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('disponible', 'Available'), ('en_proceso', 'In Progress'), ('completado', 'Completed'), ('cancelado', 'Cancelled')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='transaction_type',
            field=models.CharField(choices=[('donation', 'Donation'), ('sale', 'Sale'), ('swap', 'Swap')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='marketplace.forumquestion'),
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='product',
            field=models.ForeignKey(db_column='products_id', on_delete=django.db.models.deletion.CASCADE, related_name='forum_questions', to='marketplace.products'),
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='forum_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(db_column='products_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.products'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.RESTRICT, related_name='transactions_buying', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.OneToOneField(db_column='products_id', on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='marketplace.products'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(db_column='seller_id', on_delete=django.db.models.deletion.RESTRICT, related_name='transactions_selling', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='forumquestion',
            index=models.Index(fields=['product'], name='marketplace_product_f79f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='forumquestion',
            index=models.Index(fields=['user'], name='marketplace_user_id_df1d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='forumquestion',
            index=models.Index(fields=['parent'], name='marketplace_parent__ff447a_idx'),
        ),
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['product', 'order_number'], name='marketplace_product_1cfe7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='images',
            unique_together={('product', 'order_number')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['seller'], name='marketplace_seller__057004_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['buyer'], name='marketplace_buyer_i_e20c48_idx'),
        ),
    ]
