# Generated by Django 5.0.1 on 2026-02-24 02:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['product', 'order_number'], 'verbose_name_plural': 'Images'},
        ),
        migrations.RemoveIndex(
            model_name='forumquestion',
            name='forum_quest_product_bb78c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='images',
            name='images_product_756ae9_idx',
        ),
        migrations.RenameField(
            model_name='forumquestion',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameIndex(
            model_name='forumquestion',
            new_name='marketplace_user_id_df1d2c_idx',
            old_name='forum_quest_user_id_3d3b46_idx',
        ),
        migrations.RenameIndex(
            model_name='forumquestion',
            new_name='marketplace_parent__ff447a_idx',
            old_name='forum_quest_parent__e4b231_idx',
        ),
        migrations.RenameIndex(
            model_name='products',
            new_name='marketplace_seller__8a7591_idx',
            old_name='products_seller__c70854_idx',
        ),
        migrations.RenameIndex(
            model_name='products',
            new_name='marketplace_categor_896440_idx',
            old_name='products_categor_4083ff_idx',
        ),
        migrations.RenameIndex(
            model_name='products',
            new_name='marketplace_status_fc638b_idx',
            old_name='products_status_a30e64_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='marketplace_seller__057004_idx',
            old_name='transaction_seller__083d37_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='marketplace_buyer_i_e20c48_idx',
            old_name='transaction_buyer_i_56e41a_idx',
        ),
        migrations.AlterField(
            model_name='products',
            name='condition',
            field=models.CharField(choices=[('nuevo', 'New'), ('como_nuevo', 'Like New'), ('buen_estado', 'Good Condition'), ('usado', 'Used')], max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('disponible', 'Available'), ('en_proceso', 'In Progress'), ('completado', 'Completed'), ('cancelado', 'Cancelled')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='transaction_type',
            field=models.CharField(choices=[('donation', 'Donation'), ('sale', 'Sale'), ('swap', 'Swap')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pending'), ('confirmada', 'Confirmed'), ('completada', 'Completed'), ('cancelada', 'Cancelled')], default='pendiente', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='images',
            unique_together={('product', 'order_number')},
        ),
        migrations.AddIndex(
            model_name='forumquestion',
            index=models.Index(fields=['product'], name='marketplace_product_f79f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['product', 'order_number'], name='marketplace_product_1cfe7d_idx'),
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='forumquestion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='images',
            table=None,
        ),
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
        migrations.AlterModelTable(
            name='transaction',
            table=None,
        ),
    ]
