# Generated by Django 5.0.1 on 2026-04-23 03:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marketplace",
            "0002_comment_forumquestion_images_productreaction_report_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
