# Generated by Django 5.0.1 on 2026-04-23 03:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_add_updated_at_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwapTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("proposal_pending", "Proposal Pending"),
                            ("proposal_rejected", "Proposal Rejected"),
                            ("proposal_accepted", "Proposal Accepted"),
                            ("agenda_pending", "Agenda Pending"),
                            ("agenda_rejected", "Agenda Rejected"),
                            ("agenda_accepted", "Agenda Accepted"),
                        ],
                        default="proposal_pending",
                        max_length=30,
                    ),
                ),
                (
                    "agenda_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("proposal_decided_at", models.DateTimeField(blank=True, null=True)),
                ("agenda_decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "proposed_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="swap_proposals",
                        to="marketplace.products",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_data",
                        to="marketplace.transaction",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["transaction"], name="marketplace_transac_3d3b51_idx"
                    ),
                    models.Index(
                        fields=["proposed_product"],
                        name="marketplace_propose_add360_idx",
                    ),
                    models.Index(fields=["stage"], name="marketplace_stage_393aa5_idx"),
                    models.Index(
                        fields=["stage", "created_at"],
                        name="marketplace_stage_5bd247_idx",
                    ),
                ],
            },
        ),
    ]
