# Generated by Django 5.0.1 on 2026-03-13 01:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_fix_updated_at_products'),
        ('social', '0002_add_community_post_and_forum_post_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumquestion',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='social.communitypost'),
        ),
        migrations.AlterField(
            model_name='forumquestion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='forumquestion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='marketplace.forumquestion'),
        ),
        migrations.AlterField(
            model_name='forumquestion',
            name='product',
            field=models.ForeignKey(blank=True, db_column='products_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='marketplace.products'),
        ),
        migrations.AlterField(
            model_name='forumquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='forumquestion',
            index=models.Index(fields=['post'], name='marketplace_post_id_d7602d_idx'),
        ),
    ]
