# Generated by Django 5.0.1 on 2026-03-13 01:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='community',
            new_name='social_comm_creator_2e23ca_idx',
            old_name='social_comm_creator__067820_idx',
        ),
        migrations.RenameIndex(
            model_name='community',
            new_name='social_comm_is_acti_43796a_idx',
            old_name='social_comm_is_acti_603e93_idx',
        ),
        migrations.RenameIndex(
            model_name='communitymember',
            new_name='social_comm_communi_597aac_idx',
            old_name='social_comm_community_72f282_idx',
        ),
        migrations.RenameIndex(
            model_name='communitymember',
            new_name='social_comm_user_id_8e079b_idx',
            old_name='social_comm_user_id_1e2f77_idx',
        ),
        migrations.RenameIndex(
            model_name='communitymember',
            new_name='social_comm_communi_80923d_idx',
            old_name='social_comm_community_2af0ca_idx',
        ),
        migrations.RenameIndex(
            model_name='frequentcontact',
            new_name='social_freq_user_id_b026a8_idx',
            old_name='social_freq_user_id_373984_idx',
        ),
        migrations.RenameIndex(
            model_name='userconnection',
            new_name='social_user_request_905f22_idx',
            old_name='social_user_request_c41b9d_idx',
        ),
        migrations.RenameIndex(
            model_name='userconnection',
            new_name='social_user_address_c74be0_idx',
            old_name='social_user_addres_9d2fd3_idx',
        ),
        migrations.RenameIndex(
            model_name='userconnection',
            new_name='social_user_address_9971b5_idx',
            old_name='social_user_addres_116204_idx',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.community'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['community', 'created_at'], name='social_comm_communi_889b60_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['user'], name='social_comm_user_id_c5bdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['community', 'is_pinned'], name='social_comm_communi_039523_idx'),
        ),
    ]
