# Generated by Django 5.0.1 on 2026-02-17 03:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(), django.core.validators.RegexValidator(message='Email debe ser del dominio @iteso.mx', regex='^[^@]+@iteso\\.mx$')])),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('profile_picture', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
