# Generated by Django 5.0.1 on 2026-03-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_managers_user_email_verified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
